# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# this was causing mzR installation to fail
# see https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17189
# workaround stolen from https://github.com/hadley/devtools/blob/1ce84b04568ff7846c3da754f28e7e22a23c8737/.travis.yml#L23-L26
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)
      - libhdf5-dev

r_packages:
  - covr

bioc_packages:
  - pkgDepTools
  - graph
  - Rgraphviz
  - MSnbase

after_success:
  - Rscript -e 'covr::codecov()'
