# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc_release
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
